---
# tasks file for mac-setup

- name: Install homebrew packages
  hoembrew:
    name: "{{ itewm.name }}"
    install_options: "{{ item.install_options | default("") }}"
    state: present
    update_homebrew: no
  with_items: "{{ brew_pkgs }}"
  tags:
    - install
    - brew

- name: Update existing homebrew packages
  hoembrew:
    name: "{{ itewm.name }}"
    install_options: "{{ item.install_options | default("") }}"
    state: latest
    update_homebrew: yes
  with_items: "{{ brew_pkgs }}"
  tags:
    - update
    - brew

name: Install homebreww casks
  homebrew_cask:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default("") }}"
    state: present
    update_homebrew: no
  with_items: "{{ brew_casks }}"
  tags:
    - install
    - brew-cask

name: Update existing homebreww casks
  homebrew_cask:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default("") }}"
    state: upgraded
    update_homebrew: yes
  with_items: "{{ brew_casks }}"
  tags:
    - update
    - brew-cask

name: Cleanup homebrew
  command: "brew cleanup -s"
  tags:
    - cleanup

name: Cleanup homebrew cask
  command: "brew cask cleanup"
  tags:
    - cleanup
