---
# tasks file for mac-setup

- name: Include Homebrew variables
  include_vars:
    dir: vars/base_install

- name: Install homebrew packages
  homebrew:
    name: "{{ item }}"
    install_options: "{{ item.install_options | default('') }}"
    state: present
    update_homebrew: no
  with_items: "{{ brew_pkgs }}"
  tags:
    - install
    - brew

- name: Update existing homebrew packages
  homebrew:
    name: "{{ item }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
    update_homebrew: yes
  with_items: "{{ brew_pkgs }}"
  tags:
    - update
    - brew

- name: Install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    install_options: "{{ item.install_options | default('') }}"
    state: present
    update_homebrew: no
  with_items: "{{ brew_casks }}"
  tags:
    - install
    - brew-cask

- name: Update existing homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    install_options: "{{ item.install_options | default('') }}"
    state: upgraded
    update_homebrew: yes
  with_items: "{{ brew_casks }}"
  tags:
    - update
    - brew-cask

- name: Cleanup homebrew
  command: "brew cleanup -s"
  tags:
    - cleanup

- name: Install pip packages
  pip:
    name: "{{ item }}"
    extra_args: "{{ item.extra_args | default('') }}"
    state: present
    extra_args: --user
  with_items: "{{ pip_pkgs }}"
  tags:
    - install
    - pip

- name: Update pip packages
  pip:
    name: "{{ item }}"
    extra_args: "{{ item.extra_args | default('') }}"
    state: latest
  with_items: "{{ pip_pkgs }}"
  tags:
    - update
    - pip
