---
# tasks file for mac-setup

- name: Include image variables
  include_vars:
    dir: vars/image_pull
  tags:
    - install
    - docker
    - vagrant

- name: Ensure docker images are available
  docker_image:
    name: "{{ item }}"
    pull: yes
  with_items: "{{ docker_images }}"
  tags:
    - install
    - docker

# - name: Check if Vagrant boxes exist
#   shell: vagrant box list | grep "{{ item }}" | cat
#   register: existing_vagrant_boxes
#   with_items: "{{ vagrant_boxes }}"
#   changed_when: False

# - name: Ensure vagrant boxes are available
#   command: "vagrant box add {{ item.item }} --provider virtualbox"
#   with_items: "{{ existing_vagrant_boxes.results }}"
#   environment:
#     VAGRANT_DETECTED_OS: Darwin
#   when: not item.stdout
#   tags:
#     - install
#     - vagrant
