---
# tasks file for mac-setup

- name: Include image variables
  include_vars:
    dir: vars/image_pull
  tags:
    - install
    - docker

- name: Ensure docker images are available
  docker_image:
    name: "{{ item }}"
    pull: yes
  with_items: "{{ docker_images }}"
  tags:
    - install
    - docker

