---
# tasks file for mac-setup

- name: Include image variables
  include_vars:
    dir: vars/image_pull

- name: Ensure docker images are available
  docker_image:
    name: "{{ item }}"
    pull: yes
  with_items: "{{ docker_images }}"
  tags:
    - install
    - docker

- name: Ensure vagrant boxes are available
  command: "vagrant box add {{ item }} --provider virtualbox"
  with_items: "{{ vagrant_boxes }}"
  environment:
    VAGRANT_DETECTED_OS: Darwin
  tags:
    - install
    - vagrant
