brew_casks:
  - android-messages
  - dash
  - discord
  - docker
  - drawio
  - dropbox
  - firefox
  - flutter
  - google-chrome
  - google-drive
  - iterm2
  - microsoft-office
  - microsoft-teams
  - pop
  - postman
  - powershell
  - scroll-reverser
  - slack
  - spotify
  - steam
  - sublime-text
  - the-unarchiver
  - visual-studio-code
  - vlc
  - zoom
  - homebrew/cask-drivers/philips-hue-sync
